# ============================================================================
# 阶段1: 分解网络预训练配置
# ============================================================================

# 数据配置
data:
  # 数据集路径（需要修改为你的实际路径）
  parquet_path: "/root/autodl-tmp/qyt_contrasctivew/lmr_contrastive/dataset/pid_llvip_dataset_fixed.parquet"

  # 数据集划分文件
  split_file: "./data/dataset_split.json"

  # 数据加载参数
  batch_size: 8
  num_workers: 4
  image_size: 512

# 模型配置
model:
  # Backbone架构 (resnet18 或 resnet50)
  backbone: "resnet50"

  # 材料类别数量
  num_material_classes: 32

  # Context特征通道数
  context_channels: 8

# 损失函数权重
loss:
  lambda_intensity: 1.0    # Intensity分支权重
  lambda_material: 1.0     # Material分支权重
  lambda_context: 0.5      # Context分支权重
  lambda_fusion: 2.0       # Fusion重建权重（最重要！）

# 训练配置
training:
  num_epochs: 50           # 训练轮数
  learning_rate: 1.0e-4    # 学习率
  weight_decay: 1.0e-5     # 权重衰减
  grad_clip: 1.0           # 梯度裁剪

  # 保存间隔
  save_interval: 10        # 每N个epoch保存一次checkpoint

# 保存路径
save_dir: "./checkpoints/decomposition"
